services:
  go-image-service:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - uploads-data:/app/uploads

volumes:
  uploads-data:
