services:
  go-image-service:
    build: .
    restart: unless-stopped
    # ports:
    #   - "8080:8080"
    env_file:
      - .env
    volumes:
      - uploads-data:/app/uploads

volumes:
  uploads-data:
